package aplicacion.modelo.dominio;
// Generated 15/06/2019 05:37:58 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Atencion generated by hbm2java
 */
public class Atencion  implements java.io.Serializable {


     private Integer idAtencionMedica;
     private Date fechaAtencionMedica;
     private String diagnostico;
     private String observacion;
     private Mascota mascota;
     private PropietarioMascota propietarioMascota;
     private Medicamento medicamento;
     private Boolean estado; 

    public Atencion() {
    }

    public Atencion(Integer idAtencionMedica, Date fechaAtencionMedica, String diagnostico, String observacion, Mascota mascota, PropietarioMascota propietarioMascota, Medicamento medicamento, Boolean estado) {
        this.idAtencionMedica = idAtencionMedica;
        this.fechaAtencionMedica = fechaAtencionMedica;
        this.diagnostico = diagnostico;
        this.observacion = observacion;
        this.mascota = mascota;
        this.propietarioMascota = propietarioMascota;
        this.medicamento = medicamento;
        this.estado = estado;
    }

    public Integer getIdAtencionMedica() {
        return idAtencionMedica;
    }

    public void setIdAtencionMedica(Integer idAtencionMedica) {
        this.idAtencionMedica = idAtencionMedica;
    }

    public Date getFechaAtencionMedica() {
        return fechaAtencionMedica;
    }

    public void setFechaAtencionMedica(Date fechaAtencionMedica) {
        this.fechaAtencionMedica = fechaAtencionMedica;
    }

    public String getDiagnostico() {
        return diagnostico;
    }

    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public Mascota getMascota() {
        return mascota;
    }

    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }

    public PropietarioMascota getPropietarioMascota() {
        return propietarioMascota;
    }

    public void setPropietarioMascota(PropietarioMascota propietarioMascota) {
        this.propietarioMascota = propietarioMascota;
    }

    public Medicamento getMedicamento() {
        return medicamento;
    }

    public void setMedicamento(Medicamento medicamento) {
        this.medicamento = medicamento;
    }

    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    



}


