package aplicacion.modelo.dominio;
// Generated 15/06/2019 05:37:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Atencion generated by hbm2java
 */
public class Atencion  implements java.io.Serializable {


     private String idAtencion;
     private Date fechaAtencion;
     private String diagnostico;
     private String observacion;
     private String mascota;
     private String propietarioMascota;
     private String medicamento;
     private boolean estado;

    public Atencion() {
    }

    public Atencion(String idAtencion, Date fechaAtencion, String diagnostico, String observacion, String mascota, String propietarioMascota, String medicamento, boolean estado) {
       this.idAtencion = idAtencion;
       this.fechaAtencion = fechaAtencion;
       this.diagnostico = diagnostico;
       this.observacion = observacion;
       this.mascota = mascota;
       this.propietarioMascota = propietarioMascota;
       this.medicamento = medicamento;
       this.estado = estado;
    }
   
    public String getIdAtencion() {
        return this.idAtencion;
    }
    
    public void setIdAtencion(String idAtencion) {
        this.idAtencion = idAtencion;
    }
    public Date getFechaAtencion() {
        return this.fechaAtencion;
    }
    
    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getMascota() {
        return this.mascota;
    }
    
    public void setMascota(String mascota) {
        this.mascota = mascota;
    }
    public String getPropietarioMascota() {
        return this.propietarioMascota;
    }
    
    public void setPropietarioMascota(String propietarioMascota) {
        this.propietarioMascota = propietarioMascota;
    }
    public String getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(String medicamento) {
        this.medicamento = medicamento;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


