package aplicacion.modelo.dominio;
// Generated 15/06/2019 05:37:58 PM by Hibernate Tools 4.3.1



/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {

     // estaria faltando idDoctor??????????
     private String nombreUsuario;
     private String password;
     private String correoElectronico;
     private boolean estado;
     private String persona;

    public Doctor() {
    }

    public Doctor(String nombreUsuario, String password, String correoElectronico, boolean estado, String persona) {
       this.nombreUsuario = nombreUsuario;
       this.password = password;
       this.correoElectronico = correoElectronico;
       this.estado = estado;
       this.persona = persona;
    }
   
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getPersona() {
        return this.persona;
    }
    
    public void setPersona(String persona) {
        this.persona = persona;
    }




}


