package aplicacion.modelo.dominio;
// Generated 15/06/2019 05:37:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Medicamento generated by hbm2java
 */
public class Medicamento  implements java.io.Serializable {


     private Integer idMedicamento; // int deberia ser Integer?
     private String nombre;
     private Date fechaVencimiento;
     private String descripcion;
     private boolean estado;

    public Medicamento() {
    }

    public Medicamento(int idMedicamento, String nombre, Date fechaVencimiento, String descripcion, boolean estado) {
       this.idMedicamento = idMedicamento;
       this.nombre = nombre;
       this.fechaVencimiento = fechaVencimiento;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(int idMedicamento) {
        this.idMedicamento = idMedicamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


