package aplicacion.modelo.dominio;
// Generated 15/06/2019 05:37:58 PM by Hibernate Tools 4.3.1



/**
 * Vacuna generated by hbm2java
 */
public class Vacuna  implements java.io.Serializable {


     private int idVacuna; // Deberia ser Integer
     private String nombre;
     private String tipoVacuna;
     private boolean estado;

    public Vacuna() {
    }

    public Vacuna(int idVacuna, String nombre, String tipoVacuna, boolean estado) {
       this.idVacuna = idVacuna;
       this.nombre = nombre;
       this.tipoVacuna = tipoVacuna;
       this.estado = estado;
    }
   
    public int getIdVacuna() {
        return this.idVacuna;
    }
    
    public void setIdVacuna(int idVacuna) {
        this.idVacuna = idVacuna;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipoVacuna() {
        return this.tipoVacuna;
    }
    
    public void setTipoVacuna(String tipoVacuna) {
        this.tipoVacuna = tipoVacuna;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


